import Head from "next/head";
import { HomePage } from "@/src/components/home/home-page";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="Tutorial project" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data} />
    </>
  );
}

// This runs only on server-side and is run by Next.js before the
// component above. The page will be created just in time, after deployment.
// Note: needs to be exported as a stand-alone function
export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
